block-nuggets: 9

ores:
  DEEPSLATE:
    ITEM: GUNPOWDER
    NAME: "Deepslate"

    SILICON_NUGGET: 0.61
    ALUMINUM_NUGGET: 0.12
    POTASSIUM_NUGGET: 0.09
    SULFUR_NUGGET: 0.06
    LEAD_NUGGET: 0.05
    IRON_NUGGET: 0.04
    CARBON_PIECE: 0.01

    OTHER: 0.02

  DIORITE:
    ITEM: SUGAR
    NAME: "Diorite"

    SILICON_NUGGET: 0.51
    SODIUM_NUGGET: 0.17
    ALUMINUM_NUGGET: 0.11
    POTASSIUM_NUGGET: 0.08
    SULFUR_NUGGET: 0.03
    ZIRCONIUM_NUGGET: 0.03
    IRON_NUGGET: 0.02
    TITANIUM_NUGGET: 0.01
    NEODYMIUM_NUGGET: 0.01
    ZINC_NUGGET: 0.01

    OTHER: 0.02

  ANDESITE:
    ITEM: GUNPOWDER
    NAME: "Andesite"

    SILICON_NUGGET: 0.55
    SODIUM_NUGGET: 0.18
    POTASSIUM_NUGGET: 0.08
    ZIRCONIUM_NUGGET: 0.07
    ALUMINUM_NUGGET: 0.04
    SULFUR_NUGGET: 0.03
    IRON_NUGGET: 0.01
    ZINC_NUGGET: 0.01
    LITHIUM_NUGGET: 0.01

    OTHER: 0.02

  GRANITE:
    ITEM: REDSTONE
    NAME: "Granite"

    SILICON_NUGGET: 0.35
    IRON_NUGGET: 0.28
    SULFUR_NUGGET: 0.27
    ZINC_NUGGET: 0.06
    ZIRCONIUM_NUGGET: 0.01
    GOLD_NUGGET: 0.009
    PURE_URANIUM_NUGGET: 0.001

    OTHER: 0.02

  CALCITE:
    ITEM: SUGAR
    NAME: "Calcite"

    SILICON_NUGGET: 0.33
    SODIUM_NUGGET: 0.18
    POTASSIUM_NUGGET: 0.08
    MAGNESIUM_NUGGET: 0.08
    CARBON_PIECE: 0.08
    COPPER_NUGGET: 0.07
    SULFUR_NUGGET: 0.06
    IRON_NUGGET: 0.03
    ZINC_NUGGET: 0.04

    OTHER: 0.05

  BASALT:
    ITEM: GUNPOWDER
    NAME: "Basalt"

    SILICON_NUGGET: 0.65
    CARBON_PIECE: 0.15
    SULFUR_NUGGET: 0.10
    GOLD_NUGGET: 0.05

    OTHER: 0.05

  TUFF:
    ITEM: GUNPOWDER
    NAME: "Tuff"

    SILICON_NUGGET: 0.65
    ALUMINUM_NUGGET: 0.25
    CARBON_PIECE: 0.04
    ZINC_NUGGET: 0.01

    OTHER: 0.05

  BLACKSTONE:
    ITEM: GUNPOWDER
    NAME: "Blackstone"

    SILICON_NUGGET: 0.50
    CARBON_PIECE: 0.20
    SULFUR_NUGGET: 0.13
    GOLD_NUGGET: 0.07
    LEAD_NUGGET: 0.05

    OTHER: 0.05

  NETHERRACK:
    ITEM: REDSTONE
    NAME: "Netherrack"

    SILICON_NUGGET: 0.45
    SULFUR_NUGGET: 0.40

    OTHER: 0.15

  TERRACOTTA:
    ITEM: GLOWSTONE_DUST
    NAME: "Terracotta"

    ALUMINUM_NUGGET: 0.40
    SILICON_NUGGET: 0.35
    SODIUM_NUGGET: 0.12
    POTASSIUM_NUGGET: 0.06
    IRON_NUGGET: 0.05
    CARBON_PIECE: 0.01

    OTHER: 0.01

  DIRT:
    ITEM: GLOWSTONE_DUST
    NAME: "Dirt"

    SILICON_NUGGET: 0.45
    ALUMINUM_NUGGET: 0.30
    CARBON_PIECE: 0.15

    OTHER: 0.10

  SAND:
    ITEM: GLOWSTONE_DUST
    NAME: "Sand"

    SILICON_NUGGET: 0.95

    OTHER: 0.05

  RED_SAND:
    ITEM: GLOWSTONE_DUST
    NAME: "Red Sand"

    SILICON_NUGGET: 0.85
    IRON_NUGGET: 0.10

    OTHER: 0.05

other-percentages:
  SILICON_NUGGET: 2000
  ALUMINUM_NUGGET: 1200
  SODIUM_NUGGET: 950
  POTASSIUM_NUGGET: 350
  SULFUR_NUGGET: 150
  ZINC_NUGGET: 170
  IRON_NUGGET: 50
  ZIRCONIUM_NUGGET: 40
  COPPER_NUGGET: 20
  GOLD_NUGGET: 10
  CARBON_PIECE: 1
  NEODYMIUM_NUGGET: 0.5
  PURE_URANIUM_NUGGET: 0.1



