block-nuggets: 9

ores:
  DEEPSLATE:
    ITEM: GUNPOWDER
    NAME: "Deepslate"

    METALSMODULE:SILICON_NUGGET: 0.51
    METALSMODULE:ALUMINUM_NUGGET: 0.12
    METALSMODULE:OSMIUM_NUGGET: 0.11
    METALSMODULE:POTASSIUM_NUGGET: 0.09
    METALSMODULE:SULFUR_POWDER: 0.06
    METALSMODULE:LEAD_NUGGET: 0.04
    MINECRAFT:IRON_NUGGET: 0.03
    METALSMODULE:CARBON_POWDER: 0.01
    METALSMODULE:PHOSPHORUS_POWDER: 0.01

    OTHER: 0.02

  DIORITE:
    ITEM: SUGAR
    NAME: "Diorite"

    METALSMODULE:SILICON_NUGGET: 0.51
    METALSMODULE:SODIUM_NUGGET: 0.17
    METALSMODULE:ALUMINUM_NUGGET: 0.11
    METALSMODULE:POTASSIUM_NUGGET: 0.06
    METALSMODULE:SULFUR_POWDER: 0.03
    METALSMODULE:ZIRCONIUM_NUGGET: 0.03
    MINECRAFT:IRON_NUGGET: 0.02
    METALSMODULE:PHOSPHORUS_POWDER: 0.02
    METALSMODULE:TITANIUM_NUGGET: 0.01
    METALSMODULE:NEODYMIUM_NUGGET: 0.01
    METALSMODULE:ZINC_NUGGET: 0.01

    OTHER: 0.02

  ANDESITE:
    ITEM: GUNPOWDER
    NAME: "Andesite"

    METALSMODULE:SILICON_NUGGET: 0.55
    METALSMODULE:SODIUM_NUGGET: 0.18
    METALSMODULE:POTASSIUM_NUGGET: 0.08
    METALSMODULE:ZIRCONIUM_NUGGET: 0.07
    METALSMODULE:ALUMINUM_NUGGET: 0.04
    METALSMODULE:SULFUR_POWDER: 0.03
    MINECRAFT:IRON_NUGGET: 0.01
    METALSMODULE:ZINC_NUGGET: 0.01
    METALSMODULE:LITHIUM_NUGGET: 0.01

    OTHER: 0.02

  GRANITE:
    ITEM: REDSTONE
    NAME: "Granite"

    METALSMODULE:SILICON_NUGGET: 0.34
    MINECRAFT:IRON_NUGGET: 0.28
    METALSMODULE:SULFUR_POWDER: 0.27
    METALSMODULE:ZINC_NUGGET: 0.06
    METALSMODULE:EUROPIUM_NUGGET: 0.01
    METALSMODULE:ZIRCONIUM_NUGGET: 0.01
    MINECRAFT:GOLD_NUGGET: 0.009
    METALSMODULE:URANIUM_NUGGET: 0.001

    OTHER: 0.02

  CALCITE:
    ITEM: SUGAR
    NAME: "Calcite"

    METALSMODULE:SILICON_NUGGET: 0.33
    METALSMODULE:SODIUM_NUGGET: 0.15
    METALSMODULE:POTASSIUM_NUGGET: 0.09
    METALSMODULE:MAGNESIUM_NUGGET: 0.08
    METALSMODULE:CARBON_POWDER: 0.07
    METALSMODULE:COPPER_NUGGET: 0.06
    METALSMODULE:SULFUR_POWDER: 0.05
    METALSMODULE:PHOSPHORUS_POWDER: 0.05
    METALSMODULE:ZINC_NUGGET: 0.04
    MINECRAFT:IRON_NUGGET: 0.03

    OTHER: 0.05

  BASALT:
    ITEM: GUNPOWDER
    NAME: "Basalt"

    METALSMODULE:SILICON_NUGGET: 0.64
    METALSMODULE:CARBON_POWDER: 0.13
    METALSMODULE:BORON_PIECE: 0.07
    METALSMODULE:SULFUR_POWDER: 0.06
    MINECRAFT:GOLD_NUGGET: 0.04

    OTHER: 0.06

  TUFF:
    ITEM: GUNPOWDER
    NAME: "Tuff"

    METALSMODULE:SILICON_NUGGET: 0.63
    METALSMODULE:ALUMINUM_NUGGET: 0.26
    METALSMODULE:CARBON_POWDER: 0.03
    METALSMODULE:BORON_PIECE: 0.02
    METALSMODULE:ZINC_NUGGET: 0.01

    OTHER: 0.05

  BLACKSTONE:
    ITEM: GUNPOWDER
    NAME: "Blackstone"

    METALSMODULE:SILICON_NUGGET: 0.50
    METALSMODULE:CARBON_POWDER: 0.20
    METALSMODULE:SULFUR_POWDER: 0.13
    MINECRAFT:GOLD_NUGGET: 0.07
    METALSMODULE:LEAD_NUGGET: 0.05

    OTHER: 0.05

  NETHERRACK:
    ITEM: REDSTONE
    NAME: "Netherrack"

    METALSMODULE:SILICON_NUGGET: 0.36
    METALSMODULE:SULFUR_POWDER: 0.29
    METALSMODULE:PHOSPHORUS_POWDER: 0.09
    METALSMODULE:BORON_PIECE: 0.08
    METALSMODULE:EUROPIUM_NUGGET: 0.03

    OTHER: 0.15

  TERRACOTTA:
    ITEM: GLOWSTONEDUST
    NAME: "Terracotta"

    METALSMODULE:ALUMINUM_NUGGET: 0.40
    METALSMODULE:SILICON_NUGGET: 0.35
    METALSMODULE:SODIUM_NUGGET: 0.12
    METALSMODULE:POTASSIUM_NUGGET: 0.06
    MINECRAFT:IRON_NUGGET: 0.05
    METALSMODULE:CARBON_POWDER: 0.01

    OTHER: 0.01

  DIRT:
    ITEM: GLOWSTONEDUST
    NAME: "Dirt"

    METALSMODULE:SILICON_NUGGET: 0.44
    METALSMODULE:ALUMINUM_NUGGET: 0.30
    METALSMODULE:CARBON_POWDER: 0.13
    METALSMODULE:NEODYMIUM_NUGGET: 0.02
    METALSMODULE:EUROPIUM_NUGGET: 0.01

    OTHER: 0.10

  SAND:
    ITEM: GLOWSTONEDUST
    NAME: "Sand"

    METALSMODULE:SILICON_NUGGET: 0.94
    METALSMODULE:NEODYMIUM_NUGGET: 0.01

    OTHER: 0.05

  RED_SAND:
    ITEM: GLOWSTONEDUST
    NAME: "Red Sand"

    METALSMODULE:SILICON_NUGGET: 0.82
    MINECRAFT:IRON_NUGGET: 0.09
    METALSMODULE:EUROPIUM_NUGGET: 0.03
    METALSMODULE:NEODYMIUM_NUGGET: 0.01

    OTHER: 0.05

other-percentages:
  METALSMODULE:SILICON_NUGGET: 2000
  METALSMODULE:ALUMINUM_NUGGET: 1200
  METALSMODULE:SODIUM_NUGGET: 950
  METALSMODULE:POTASSIUM_NUGGET: 350
  METALSMODULE:SULFUR_POWDER: 150
  METALSMODULE:ZINC_NUGGET: 170
  MINECRAFT:IRON_NUGGET: 50
  METALSMODULE:ZIRCONIUM_NUGGET: 40
  METALSMODULE:COPPER_NUGGET: 20
  MINECRAFT:GOLD_NUGGET: 10
  METALSMODULE:CARBON_POWDER: 1
  METALSMODULE:NEODYMIUM_NUGGET: 0.5
  METALSMODULE:URANIUM_NUGGET: 0.1



